version: '3'

services:
  app:
    image: blogapp:1.0
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://db:5432/blog
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"