spring:
  application:
    name: BlogDemo
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

jwt:
  secret: REFOSVNBQkRVTEdBWklaT1ZEQU5JU0FCRFVMR0FaSVpPVkRBTklTQUJEVUxHQVpJWk9W
  expiration: 3600000