spring:
  application:
    name: BlogDemo
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/blog
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: REFOSVNBQkRVTEdBWklaT1ZEQU5JU0FCRFVMR0FaSVpPVkRBTklTQUJEVUxHQVpJWk9W
  expiration: 3600000